const LOGOS = 'logos/teams';

export const TEAMS = [
  { slug: 'ducks', label: 'Anaheim Ducks', abbr: 'ANA', color: '#F47A38', logo: `${LOGOS}/anaheim_ducks.png` },
  { slug: 'coyotes', label: 'Arizona Coyotes', abbr: 'ARI', color: '#8C2633', logo: `${LOGOS}/arizona_coyotes.png` },
  { slug: 'bruins', label: 'Boston Bruins', abbr: 'BOS', color: '#FFB81C', logo: `${LOGOS}/boston_bruins.png` },
  { slug: 'sabres', label: 'Buffalo Sabres', abbr: 'BUF', color: '#FCB514', logo: `${LOGOS}/buffalo_sabres.png` },
  { slug: 'flames', label: 'Calgary Flames', abbr: 'CGY', color: '#C8102E', logo: `${LOGOS}/calgary_flames.png` },
  { slug: 'hurricanes', label: 'Carolina Hurricanes', abbr: 'CAR', color: '#CC0000', logo: `${LOGOS}/carolina_hurricanes.png` },
  { slug: 'blackhawks', label: 'Chicago Blackhawks', abbr: 'CHI', color: '#CF0A2C', logo: `${LOGOS}/chicago_blackhawks.png` },
  { slug: 'avalanche', label: 'Colorado Avalanche', abbr: 'COL', color: '#6F263D', logo: `${LOGOS}/colorado_avalanche.png` },
  { slug: 'blue-jackets', label: 'Columbus Blue Jackets', abbr: 'CBJ', color: '#002654', logo: `${LOGOS}/columbus_blue_jackets.png` },
  { slug: 'stars', label: 'Dallas Stars', abbr: 'DAL', color: '#006847', logo: `${LOGOS}/dallas_stars.png` },
  { slug: 'red-wings', label: 'Detroit Red Wings', abbr: 'DET', color: '#CE1126', logo: `${LOGOS}/detroit_red_wings.png` },
  { slug: 'oilers', label: 'Edmonton Oilers', abbr: 'EDM', color: '#FF4C00', logo: `${LOGOS}/edmonton_oilers.png` },
  { slug: 'panthers', label: 'Florida Panthers', abbr: 'FLA', color: '#C8102E', logo: `${LOGOS}/florida_panthers.png` },
  { slug: 'kings', label: 'Los Angeles Kings', abbr: 'LAK', color: '#A2AAAD', logo: `${LOGOS}/los_angeles_kings.png` },
  { slug: 'wild', label: 'Minnesota Wild', abbr: 'MIN', color: '#154734', logo: `${LOGOS}/minnesota_wild.png` },
  { slug: 'canadiens', label: 'Montreal Canadiens', abbr: 'MTL', color: '#AF1E2D', logo: `${LOGOS}/montreal_canadiens.png` },
  { slug: 'predators', label: 'Nashville Predators', abbr: 'NSH', color: '#FFB81C', logo: `${LOGOS}/nashville_predators.png` },
  { slug: 'devils', label: 'New Jersey Devils', abbr: 'NJD', color: '#CE1126', logo: `${LOGOS}/new_jersey_devils.png` },
  { slug: 'islanders', label: 'New York Islanders', abbr: 'NYI', color: '#00539B', logo: `${LOGOS}/new_york_islanders.png` },
  { slug: 'rangers', label: 'New York Rangers', abbr: 'NYR', color: '#0038A8', logo: `${LOGOS}/new_york_rangers.png` },
  { slug: 'senators', label: 'Ottawa Senators', abbr: 'OTT', color: '#C8102E', logo: `${LOGOS}/ottawa_senators.png` },
  { slug: 'flyers', label: 'Philadelphia Flyers', abbr: 'PHI', color: '#F74902', logo: `${LOGOS}/philadelphia_flyers.png` },
  { slug: 'penguins', label: 'Pittsburgh Penguins', abbr: 'PIT', color: '#FCB514', logo: `${LOGOS}/pittsburgh_penguins.png` },
  { slug: 'sharks', label: 'San Jose Sharks', abbr: 'SJS', color: '#006D75', logo: `${LOGOS}/san_jose_sharks.png` },
  { slug: 'kraken', label: 'Seattle Kraken', abbr: 'SEA', color: '#99D9D9', logo: `${LOGOS}/seattle_kraken.png` },
  { slug: 'blues', label: 'St. Louis Blues', abbr: 'STL', color: '#002F87', logo: `${LOGOS}/st_louis_blues.png` },
  { slug: 'lightning', label: 'Tampa Bay Lightning', abbr: 'TBL', color: '#002868', logo: `${LOGOS}/tampa_bay_lightning.png` },
  { slug: 'maple-leafs', label: 'Toronto Maple Leafs', abbr: 'TOR', color: '#00205B', logo: `${LOGOS}/toronto_maple_leafs.png` },
  { slug: 'mammoth', label: 'Utah Mammoth', abbr: 'UTA', color: '#71AFE5', logo: `${LOGOS}/utah_mammoth.png` },
  { slug: 'canucks', label: 'Vancouver Canucks', abbr: 'VAN', color: '#00843D', logo: `${LOGOS}/vancouver_canucks.png` },
  { slug: 'golden-knights', label: 'Vegas Golden Knights', abbr: 'VGK', color: '#C9A84C', logo: `${LOGOS}/vegas_golden_knights.png` },
  { slug: 'capitals', label: 'Washington Capitals', abbr: 'WSH', color: '#C8102E', logo: `${LOGOS}/washington_capitals.png` },
  { slug: 'jets', label: 'Winnipeg Jets', abbr: 'WPG', color: '#041E42', logo: `${LOGOS}/winnipeg_jets.png` },
  { slug: 'all-star-4-nations', label: 'All Star Game/4 Nations', abbr: 'ASG', color: '#9CA3AF', logo: `${LOGOS}/4_nations.png` },
];
